@echo off
echo Applying migrations...
python manage.py migrate
echo Creating superuser if none exists...
python manage.py create_superuser_if_none
echo Running Django development server...
python manage.py runserver %*
