# Generated by Django 5.2.4 on 2025-07-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('community', 'Community Member'), ('staff', 'Staff Member')], default='community', max_length=10),
        ),
    ]
